/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Mainpackage;

import Mainpackage.PanelForm;
import SwingPack.PanelSlide1;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;



/**
 *
 * @author Sam
 */
public class CalenderForm extends javax.swing.JPanel {

    /**
     * Creates new form CalenderForm
     */
    private int month,Year;
    public CalenderForm() {
        initComponents();
        thisMonth();
        Slider.show(new PanelForm(28,2023), PanelSlide1.AnimateType.TO_RIGHT);
        MonthYear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Slider = new SwingPack.PanelSlide1();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTime = new javax.swing.JLabel();
        jPm = new javax.swing.JLabel();
        jDay = new javax.swing.JLabel();
        jForward = new javax.swing.JButton();
        jBack = new javax.swing.JButton();
        jTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        Slider.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jPanel2.setBackground(new java.awt.Color(208, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jTime.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jTime.setForeground(new java.awt.Color(51, 51, 55));
        jTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jTime.setText("8:04:00");

        jPm.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPm.setForeground(new java.awt.Color(51, 51, 55));
        jPm.setText("am");

        jDay.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jDay.setForeground(new java.awt.Color(51, 51, 55));
        jDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDay.setText("Day");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTime, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPm, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDay, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDay, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jForward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ForwardIcon.jpg"))); // NOI18N
        jForward.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jForwardActionPerformed(evt);
            }
        });

        jBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Backwards.jpg"))); // NOI18N
        jBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });

        jTitle.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jTitle.setForeground(new java.awt.Color(51, 51, 55));
        jTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitle.setText("Calendar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jForward, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jForward, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
        if(month == 1 )
        {
            month = 12;
            Year--;
        }
        else 
        {
            month--;
        }
        Slider.show(new PanelForm(month, Year), PanelSlide1.AnimateType.TO_RIGHT);
        MonthYear();
    }//GEN-LAST:event_jBackActionPerformed

    private void jForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jForwardActionPerformed
        // TODO add your handling code here:
        if(month == 12 )
        {
            month = 1;
            Year++;
        }
        else 
        {
            month++;
        }
        Slider.show(new PanelForm(month, Year), PanelSlide1.AnimateType.TO_LEFT);
        MonthYear();
        new Thread(new Runnable() {
            @Override
            public void run() {
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            while(true){
                try {
                    Thread.sleep(1000); 
                } catch (InterruptedException e) {
                    System.err.println(e);
                }
                SimpleDateFormat time = new SimpleDateFormat("hh:mm:ss aa");
                SimpleDateFormat date = new SimpleDateFormat("EEEE, dd/mm/yyyy");
                Date date1 = new Date();
                jDay.setText(date.format(date1));
                String tm = time.format(date1);
                //jDay.setText(tm.split(" ")[0]);
                jPm.setText(tm.split(" ")[1]);
                jTime.setText(tm.split(" ")[0]);
            }
            }
        }).start();
    }//GEN-LAST:event_jForwardActionPerformed
    private void thisMonth()
    {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(new Date());  //This is today's date
        month = calendar.get(Calendar.MONTH)+1;
        Year = calendar.get(Calendar.YEAR);
        //return 1;
    }
    
    private void MonthYear()
    {
        Calendar calendar =Calendar.getInstance();
        calendar.set(Calendar.MONTH, month-1); //To allow months to start from xero as january
        calendar.set(Calendar.YEAR, Year);
        calendar.set(Calendar.DATE, 1);
        SimpleDateFormat date = new SimpleDateFormat("MMM-YYYY");
        jTitle.setText(date.format(calendar.getTime()));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SwingPack.PanelSlide1 Slider;
    private javax.swing.JButton jBack;
    private javax.swing.JLabel jDay;
    private javax.swing.JButton jForward;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jPm;
    private javax.swing.JLabel jTime;
    private javax.swing.JLabel jTitle;
    // End of variables declaration//GEN-END:variables
}
