/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Mainpackage;

import java.awt.Component;
import java.util.Calendar;
import java.util.Date;
import main.Cell;
import main.ToDay;

/**
 *
 * @author Sam
 */
public class PanelForm extends javax.swing.JLayeredPane {

    /**
     * Creates new form PanelForm
     */
    int Month, Year;
    public PanelForm(int Month, int Year) {

        initComponents();
        this.Month = Month;
        this.Year = Year;
        init();
    }
    public void init()
    {
    Monday.asTitle();
    Tuesday.asTitle();
    Wednesday.asTitle();
    Thursday.asTitle();
    Friday.asTitle();
    Saturday.asTitle();
    Sunday.asTitle();
    setDate();
    
    }
    private void setDate()
    {
        Calendar calender =  Calendar.getInstance();
        calender.set(Calendar.YEAR, Year);
        calender.set(Calendar.MONTH, Month-1); //To set the month January as Zero
        calender.set(Calendar.DATE, 1);
        int StartDay = calender.get(Calendar.DAY_OF_WEEK) - 1;
        calender.add(Calendar.DATE, -StartDay);
        ToDay toDay = getToday();
        for(Component comp: getComponents())
        {
           Cells cell = (Cells) comp;
           if(!cell.isTitle())
           {
               cell.setText(calender.get(Calendar.DATE)+ "");
               cell.setDate(calender.getTime());
               cell.currentMonth(calender.get(Calendar.MONTH) == Month - 1);
               if(toDay.isToDay(new ToDay(calender.get(Calendar.DATE), calender.get(Calendar.MONTH)+1 , calender.get(Calendar.YEAR))))
               {
                   cell.setdaytoday();
               }
               calender.add(Calendar.DATE, 1);  //Increase date by one
           }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private ToDay getToday()
    {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(new Date());
        return new ToDay(calendar.get(Calendar.DATE), calendar.get(Calendar.MONTH)+1, calendar.get(Calendar.YEAR));
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sunday = new Mainpackage.Cells();
        Monday = new Mainpackage.Cells();
        Tuesday = new Mainpackage.Cells();
        Wednesday = new Mainpackage.Cells();
        Thursday = new Mainpackage.Cells();
        Friday = new Mainpackage.Cells();
        Saturday = new Mainpackage.Cells();
        cells8 = new Mainpackage.Cells();
        cells9 = new Mainpackage.Cells();
        cells10 = new Mainpackage.Cells();
        cells11 = new Mainpackage.Cells();
        cells12 = new Mainpackage.Cells();
        cells13 = new Mainpackage.Cells();
        cells14 = new Mainpackage.Cells();
        cells15 = new Mainpackage.Cells();
        cells16 = new Mainpackage.Cells();
        cells17 = new Mainpackage.Cells();
        cells18 = new Mainpackage.Cells();
        cells19 = new Mainpackage.Cells();
        cells20 = new Mainpackage.Cells();
        cells21 = new Mainpackage.Cells();
        cells22 = new Mainpackage.Cells();
        cells23 = new Mainpackage.Cells();
        cells24 = new Mainpackage.Cells();
        cells25 = new Mainpackage.Cells();
        cells26 = new Mainpackage.Cells();
        cells27 = new Mainpackage.Cells();
        cells28 = new Mainpackage.Cells();
        cells29 = new Mainpackage.Cells();
        cells30 = new Mainpackage.Cells();
        cells31 = new Mainpackage.Cells();
        cells32 = new Mainpackage.Cells();
        cells33 = new Mainpackage.Cells();
        cells34 = new Mainpackage.Cells();
        cells35 = new Mainpackage.Cells();
        cells36 = new Mainpackage.Cells();
        cells37 = new Mainpackage.Cells();
        cells38 = new Mainpackage.Cells();
        cells39 = new Mainpackage.Cells();
        cells40 = new Mainpackage.Cells();
        cells41 = new Mainpackage.Cells();
        cells42 = new Mainpackage.Cells();
        cells43 = new Mainpackage.Cells();
        cells44 = new Mainpackage.Cells();
        cells45 = new Mainpackage.Cells();
        cells46 = new Mainpackage.Cells();
        cells47 = new Mainpackage.Cells();
        cells48 = new Mainpackage.Cells();
        cells49 = new Mainpackage.Cells();

        setLayout(new java.awt.GridLayout(7, 7));

        Sunday.setBackground(new java.awt.Color(0, 0, 255));
        Sunday.setForeground(new java.awt.Color(255, 51, 0));
        Sunday.setText("Sun");
        add(Sunday);

        Monday.setText("Mon");
        add(Monday);

        Tuesday.setText("Tues");
        add(Tuesday);

        Wednesday.setText("Wed");
        Wednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WednesdayActionPerformed(evt);
            }
        });
        add(Wednesday);

        Thursday.setText("Thur");
        add(Thursday);

        Friday.setText("Fri");
        add(Friday);

        Saturday.setText("Sat");
        add(Saturday);

        cells8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells8);

        cells9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells9);

        cells10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells10);

        cells11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells11);

        cells12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells12);

        cells13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells13);

        cells14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells14);

        cells15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells15);

        cells16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells16);

        cells17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells17);

        cells18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells18);

        cells19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells19);

        cells20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells20);

        cells21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells21);

        cells22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells22);

        cells23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells23);

        cells24.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells24);

        cells25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells25);

        cells26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells26);

        cells27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells27);

        cells28.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells28);

        cells29.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells29);

        cells30.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells30);

        cells31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells31);

        cells32.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells32);

        cells33.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells33);

        cells34.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells34);

        cells35.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells35);

        cells36.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells36);

        cells37.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells37);

        cells38.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells38);

        cells39.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells39);

        cells40.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells40);

        cells41.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells41);

        cells42.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells42);

        cells43.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells43);

        cells44.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells44);

        cells45.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells45);

        cells46.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells46);

        cells47.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells47);

        cells48.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells48);

        cells49.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cells49);
    }// </editor-fold>//GEN-END:initComponents

    private void WednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WednesdayActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_WednesdayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Mainpackage.Cells Friday;
    private Mainpackage.Cells Monday;
    private Mainpackage.Cells Saturday;
    private Mainpackage.Cells Sunday;
    private Mainpackage.Cells Thursday;
    private Mainpackage.Cells Tuesday;
    private Mainpackage.Cells Wednesday;
    private Mainpackage.Cells cells10;
    private Mainpackage.Cells cells11;
    private Mainpackage.Cells cells12;
    private Mainpackage.Cells cells13;
    private Mainpackage.Cells cells14;
    private Mainpackage.Cells cells15;
    private Mainpackage.Cells cells16;
    private Mainpackage.Cells cells17;
    private Mainpackage.Cells cells18;
    private Mainpackage.Cells cells19;
    private Mainpackage.Cells cells20;
    private Mainpackage.Cells cells21;
    private Mainpackage.Cells cells22;
    private Mainpackage.Cells cells23;
    private Mainpackage.Cells cells24;
    private Mainpackage.Cells cells25;
    private Mainpackage.Cells cells26;
    private Mainpackage.Cells cells27;
    private Mainpackage.Cells cells28;
    private Mainpackage.Cells cells29;
    private Mainpackage.Cells cells30;
    private Mainpackage.Cells cells31;
    private Mainpackage.Cells cells32;
    private Mainpackage.Cells cells33;
    private Mainpackage.Cells cells34;
    private Mainpackage.Cells cells35;
    private Mainpackage.Cells cells36;
    private Mainpackage.Cells cells37;
    private Mainpackage.Cells cells38;
    private Mainpackage.Cells cells39;
    private Mainpackage.Cells cells40;
    private Mainpackage.Cells cells41;
    private Mainpackage.Cells cells42;
    private Mainpackage.Cells cells43;
    private Mainpackage.Cells cells44;
    private Mainpackage.Cells cells45;
    private Mainpackage.Cells cells46;
    private Mainpackage.Cells cells47;
    private Mainpackage.Cells cells48;
    private Mainpackage.Cells cells49;
    private Mainpackage.Cells cells8;
    private Mainpackage.Cells cells9;
    // End of variables declaration//GEN-END:variables
}
