/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.util.Arrays;

/**
 *
 * @author Sam
 */
public class MyGuiForm extends javax.swing.JFrame {

    /**
     * Creates new form MyGuiForm
     */
    public MyGuiForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editorc.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        UsernameTF = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDef=====aultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 60, 40));

        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, 40));

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, 20));

        UsernameTF.setText("Username");
        UsernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTFActionPerformed(evt);
            }
        });
        UsernameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsernameTFKeyTyped(evt);
            }
        });
        getContentPane().add(UsernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 90, -1));

        jToolBar1.setRollover(true);
        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField1.setText("CPUT SOS");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 140, 50));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 70, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton1.setText("Log In");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         String username = UsernameTF.getText();
          char[] password = jPasswordField1.getPassword(); 
           if (authenticate(username, password)) {
        // Authentication successful
        System.out.println("Authentication successful!");
    } else {
        // Authentication failed
        System.out.println("Authentication failed!");
    }
    }                                        

    private void UsernameTFActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        //String UsernameTF = "Samukelo";ojorg
         
   // Note: getPassword returns a char array

    // Perform authentication here (replace with your actual authentication logic)
  
}    

private boolean authenticate(String username, char[] password) {
    // Replace this with your actual authentication logic
    // For example, compare the username and password with stored values
    String storedUsername = "Samukelo";
    String storedPassword = "password123"; // Replace with actual stored password
    return username.equals(storedUsername) && String.valueOf(password).equals(storedPassword);
}                                         

import java.awt.event.ActionEvent;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class MyGuiForm extends JFrame {
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JPasswordField jPasswordField1;
    private JTextField usernameTF;
    private JButton loginButton;
    private JButton exitButton;

    public MyGuiForm() {
        initComponents();
    }

    private void initComponents() {
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jPasswordField1 = new JPasswordField();
        usernameTF = new JTextField();
        loginButton = new JButton();
        exitButton = new JButton();

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 80, 60, 40);

        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 140, 60, 40);

        jPasswordField1.setText("jPasswordField1");
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(300, 150, 120, 20);

        usernameTF.setText("Username");
        getContentPane().add(usernameTF);
        usernameTF.setBounds(300, 90, 120, 20);

        loginButton.setText("Log In");
        loginButton.addActionListener((ActionEvent evt) -> {
            String username = usernameTF.getText();
            char[] password = jPasswordField1.getPassword();
            if (authenticate(username, password)) {
                // Authentication successful
                System.out.println("Authentication successful!");
            } else {
                // Authentication failed
                System.out.println("Authentication failed!");
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(300, 190, 80, 25);

        exitButton.setText("Exit");
        exitButton.addActionListener((ActionEvent evt) -> {
            System.exit(0);
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(300, 230, 70, 25);

        pack();
    }

    private boolean authenticate(String username, char[] password) {
        // Replace this with your actual authentication logic
        // For example, compare the username and password with stored values
        String storedUsername = "Samukelo";
        String storedPassword = "password123"; // Replace with actual stored password
        return username.equals(storedUsername) && Arrays.equals(password, storedPassword.toCharArray());
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new MyGuiForm().setVisible(true);
        });
    }
}
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    private void UsernameTFKeyTyped(java.awt.event.KeyEvent evt) {                                    
        // TODO add your handling code here:

    }                                   

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
    @Override
    public void focusGained(java.awt.event.FocusEvent evt) {
        jPasswordField1.setText("Password123");
    }
});

    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyGuiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyGuiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyGuiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyGuiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyGuiForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration                   
}
